apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-proxy-conf
data:
  nginx.conf: |
    worker_processes  1;

    events {
        worker_connections  1024;
    }

    http {
        default_type  application/octet-stream;

        sendfile        on;

        keepalive_timeout  65000;

        server {
            listen       80;
            server_name  localhost;

            location /v1/backend-api/ {
                add_header Allow "GET, POST, HEAD" always;
                proxy_http_version 1.1;
                proxy_cache_bypass $http_upgrade;

                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $http_host;
                proxy_set_header X-Forwarded-Host $http_host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Access-Control-Allow-Origin *;
                proxy_set_header Access-Control-Allow-Methods 'GET, POST, OPTIONS, PUT, DELETE';
                proxy_set_header Access-Control-Allow-Credentials true;
                proxy_set_header Access-Control-Allow-Headers Origin,Content-Type,Accept;
                proxy_pass      http://backend-api-svc:3003/api/;
                proxy_redirect off;
                rewrite ^/api/backend-api(/.*)$ $1 break;
            }

            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                root   html;
            }

        }
    }
  