apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: backend-proxy-conf
  files:
  - nginx.conf
resources:
  - resources/deployment.yaml
  - resources/service.yaml
patchesStrategicMerge:
  - limits/limit.yaml
images:
- name: nginx
  newTag: 1.17.4