kind: Deployment
apiVersion: apps/v1
metadata:
  name: todo-api
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: todo-api
        resources:
          limits:
            memory: 128Mi