kind: Service
apiVersion: v1
metadata:
  name: frontend-svc
  labels:
    app: frontend
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: frontend
  type: LoadBalancer