apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express:latest
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          value: root
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          value: techtalk
        - name: ME_CONFIG_MONGODB_URL
          value: mongodb://root:techtalk@mongodb-svc.todo-app:27017/
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 100m
            memory: 128Mi