kind: Service
apiVersion: v1
metadata:
  name: backend-api-svc
  labels:
    app: backend-api
spec:
  ports:
    - protocol: TCP
      port: 3003
  selector:
    app: backend-api
  clusterIP: None
  type: ClusterIP