apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-proxy
  labels:
    app: backend-proxy
spec:
  selector:
    matchLabels:
      app: backend-proxy
  template:
    metadata:
      labels:
        app: backend-proxy
    spec:
      containers:
      - name: backend-proxy
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx
          readOnly: true
          name: backend-proxy-conf
      volumes:
      - name: backend-proxy-conf
        configMap:
          name: backend-proxy-conf
          items:
            - key: nginx.conf
              path: nginx.conf