kind: Service
apiVersion: v1
metadata:
  name: lab-nginx-srvc
  labels:
    app: lab-nginx
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: lab-nginx
  type: NodePort
  externalTrafficPolicy: Cluster