kind: Service
apiVersion: v1
metadata:
  name: backend-proxy-srvc
  labels:
    app: backend-proxy
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: backend-proxy
  type: NodePort
  externalTrafficPolicy: Cluster