kind: Service
apiVersion: v1
metadata:
  name: mongodb-svc
  labels:
    app: mongodb
spec:
  ports:
    - protocol: TCP
      port: 27017
  selector:
    app: mongodb
  clusterIP: None
  type: ClusterIP