kind: Service
apiVersion: v1
metadata:
  name: user-interface-srvc
  labels:
    app: user-interface
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
  selector:
    app: user-interface
  type: NodePort
  externalTrafficPolicy: Cluster