apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  labels:
    app: backend-api
spec:
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
      - name: backend-api
        envFrom:
        - configMapRef:
            name: backend-api-props
        image: earthworm013/minikube-lab-backend:1.0.0
        ports:
        - containerPort: 3003