kind: Service
apiVersion: v1
metadata:
  name: todo-api-internal-srvc
  labels:
    app: todo-api
spec:
  ports:
    - protocol: TCP
      port: 3003
  selector:
    app: todo-api
  clusterIP: None
  type: ClusterIP