kind: Service
apiVersion: v1
metadata:
  name: todo-api-external-srvc
  labels:
    app: todo-api
spec:
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
      nodePort: 30003
  selector:
    app: todo-api
  type: NodePort
  externalTrafficPolicy: Cluster