kind: Service
apiVersion: v1
metadata:
  name: todo-app-internal-srvc
  labels:
    app: todo-app
spec:
  ports:
    - protocol: TCP
      port: 3003
  selector:
    app: todo-app
  clusterIP: None
  type: ClusterIP